# Generated by Django 6.0.1 on 2026-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('curso_interesse', models.CharField(blank=True, help_text='Qual curso o lead está interessado', max_length=255, null=True)),
                ('mensagem_original', models.TextField(blank=True, help_text='Primeira mensagem/dúvida do lead')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contato', 'Contato Realizado'), ('interessa', 'Interessado'), ('negociacao', 'Em Negociação'), ('convertido', 'Convertido'), ('perdido', 'Lead Perdido')], default='novo', max_length=20)),
                ('prioridade', models.IntegerField(default=0, help_text='0=baixa, 1=média, 2=alta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vendedor_responsavel', models.CharField(blank=True, help_text='Email do vendedor responsável', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre o lead')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='vendas_bot__status_1fdd75_idx'), models.Index(fields=['email'], name='vendas_bot__email_0a3cd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(help_text='Nome do curso (ex: Administração, Engenharia)', max_length=255)),
                ('valor_integral', models.DecimalField(decimal_places=2, help_text='Valor para pagamento à vista', max_digits=10)),
                ('parcelas', models.IntegerField(default=12, help_text='Número de parcelas disponíveis')),
                ('valor_parcela', models.DecimalField(decimal_places=2, help_text='Valor de cada parcela', max_digits=10)),
                ('desconto_percentual', models.IntegerField(default=0, help_text='Percentual de desconto (se houver)')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da oferta')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informação de Preço',
                'verbose_name_plural': 'Informações de Preço',
                'ordering': ['curso_nome'],
                'unique_together': {('curso_nome',)},
            },
        ),
        migrations.CreateModel(
            name='VendasAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('leads_novo', models.IntegerField(default=0)),
                ('leads_contato', models.IntegerField(default=0)),
                ('leads_convertidos', models.IntegerField(default=0)),
                ('taxa_conversao', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Analytic de Vendas',
                'verbose_name_plural': 'Analytics de Vendas',
                'ordering': ['-data'],
                'unique_together': {('data',)},
            },
        ),
    ]
