# Generated by Django 6.0.1 on 2026-01-26 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único do bot (ex: cursos_bot, vendas_bot)', max_length=100, unique=True)),
                ('bot_type', models.CharField(choices=[('cursos', 'Bot de Cursos'), ('vendas', 'Bot de Vendas'), ('suporte', 'Bot de Suporte'), ('leads', 'Bot de Leads'), ('custom', 'Bot Customizado')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição do bot e seu propósito')),
                ('bot_token', models.CharField(help_text='Token único para validar requisições (gerado pelo Chatwoot)', max_length=255, unique=True)),
                ('webhook_url', models.CharField(help_text='URL do webhook (ex: https://api.aiprati.com.br/api/v1/cursos/webhook/)', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não processará mensagens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_request', models.DateTimeField(blank=True, help_text='Timestamp da última requisição', null=True)),
                ('request_count', models.BigIntegerField(default=0, help_text='Total de requisições processadas')),
            ],
            options={
                'verbose_name': 'Agent Bot',
                'verbose_name_plural': 'Agent Bots',
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['bot_token'], name='bots_agentb_bot_tok_c57904_idx'), models.Index(fields=['is_active', 'name'], name='bots_agentb_is_acti_ee8be6_idx')],
            },
        ),
    ]
